DROP MATERIALIZED VIEW IF EXISTS stock_screening_view;

ALTER TABLE stocks ALTER COLUMN ticker TYPE VARCHAR(20);
ALTER TABLE daily_prices ALTER COLUMN ticker TYPE VARCHAR(20);
ALTER TABLE fundamentals ALTER COLUMN ticker TYPE VARCHAR(20);
ALTER TABLE technical_indicators ALTER COLUMN ticker TYPE VARCHAR(20);

